/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Consultation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
  'getPageVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'recordPageVisit' : IDL.Func([], [], []),
  'submitConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateConsultationStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Consultation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
    'getPageVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'recordPageVisit' : IDL.Func([], [], []),
    'submitConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateConsultationStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };